### ISSUE TITLE
Schematic and PCB error

### ISSUE THREAD

**Issue by ngoslee-ttt** [adafruit/Adafruit-TXB0104-Level-Shifter-Breakout-PCB#1]
The IC symbol for the TXB0104 has GND (pin 7) typed as io instead of pwr. As a result, Eagle is not connecting this pin to the GND net. The PCB has no connection the pin, and the breakout board does not work.
See also: https://forums.adafruit.com/viewtopic.php?f=19&t=108306
![txb0104_pcb_nc](https://cloud.githubusercontent.com/assets/25062758/21860349/516b2244-d7fe-11e6-9def-d780ad361869.png)

Nathan

**Comment by ladyada** [comment]
hiya, thanks - this was already brought up in an issue and is fixed in next version. email support@adafruit for a refund

**Comment by ngoslee-ttt** [comment]
Hiya back, 
Yah, you may be referred to the thread I started on your forums. I had thought the design issue was addressed until the post on Jan 05 from adafruit_support_mike so I decided to chase it into the ground. 
Nathan
On Jan 11, 2017 1:25 PM, ladyada <notifications@github.com> wrote:hiya, thanks - this was already brought up in an issue and is fixed in next version. email support@adafruit for a refund

**Comment by ladyada** [comment]
all good :)
