### ISSUE TITLE
GND pin not connected

### ISSUE THREAD

**Issue by Cyrilanthony777** [adafruit/Adafruit-TXB0104-Level-Shifter-Breakout-PCB#2]
GND pin on the TXB0104 IC is not connected to PCB GND

**Comment by ladyada** [comment]
@kattni please update these with rev C :)

**Comment by kattni** [comment]
@Cyrilanthony777 Files have been updated with rev C.

**Comment by Cyrilanthony777** [comment]
Thanks :)
